# Generated by Django 2.1.1 on 2019-02-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_model',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='question_model',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='question_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
