# Generated by Django 2.1.1 on 2019-02-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_auto_20190209_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_model',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='question_model',
            name='longitude',
        ),
        migrations.AddField(
            model_name='question_model',
            name='top_level',
            field=models.IntegerField(default=20),
        ),
    ]
