# Generated by Django 2.1.1 on 2019-02-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0004_auto_20190215_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_model',
            name='file_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question_model',
            name='line',
            field=models.BooleanField(default=False),
        ),
    ]
