# Generated by Django 2.1.5 on 2019-02-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0005_auto_20190215_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_model',
            name='top_level',
            field=models.IntegerField(default=34),
        ),
    ]
