# Generated by Django 2.1 on 2019-02-06 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username2', models.CharField(max_length=100, null=True)),
                ('username3', models.CharField(max_length=100, null=True)),
                ('username4', models.CharField(max_length=100, null=True)),
                ('username5', models.CharField(max_length=100, null=True)),
                ('email1', models.EmailField(max_length=254)),
                ('email2', models.EmailField(max_length=254, null=True)),
                ('email3', models.EmailField(max_length=254, null=True)),
                ('email4', models.EmailField(max_length=254, null=True)),
                ('email5', models.EmailField(max_length=254, null=True)),
                ('branch1', models.CharField(max_length=100)),
                ('branch2', models.CharField(max_length=100, null=True)),
                ('branch3', models.CharField(max_length=100, null=True)),
                ('branch4', models.CharField(max_length=100, null=True)),
                ('branch5', models.CharField(max_length=100, null=True)),
                ('contact1', models.IntegerField()),
                ('contact2', models.IntegerField(null=True)),
                ('contact3', models.IntegerField(null=True)),
                ('contact4', models.IntegerField(null=True)),
                ('contact5', models.IntegerField(null=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
