# Generated by Django 2.1 on 2019-02-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_detail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='branch4',
            new_name='participant2',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='branch5',
            new_name='participant3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contact4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contact5',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email5',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username5',
        ),
        migrations.AddField(
            model_name='profile',
            name='leadername',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
