# Generated by Django 2.1.1 on 2019-02-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_detail', '0004_auto_20190209_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='attempts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
