# Generated by Django 2.1.1 on 2019-02-15 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_detail', '0007_profile_freeze'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='freeze',
        ),
    ]
