# Generated by Django 2.1.1 on 2019-02-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_detail', '0008_remove_profile_freeze'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='freeze',
            field=models.BooleanField(default=False),
        ),
    ]
