# Generated by Django 2.1.1 on 2019-02-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_detail', '0018_auto_20190216_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
