# Generated by Django 2.1.5 on 2019-02-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_detail', '0019_profile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='q10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='q5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='q6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='q7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='q8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='q9',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=4),
        ),
    ]
