# Generated by Django 2.1.5 on 2019-02-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_detail', '0020_auto_20190219_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='poi',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
