# Generated by Django 2.1.5 on 2019-02-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_detail', '0021_profile_poi'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tuh',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='poi',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
